// Original teaching drafts. Source links describe the curriculum, not ownership
// or endorsement of these questions. Subject-expert review is still required.
export const bankVersion = 'learn-draft-2026-09-26';
export const tracks = {
  foundation: {title:'Medical undergraduate', description:'Understand the question, choose the method, interpret the result.'},
  medicine: {title:'Postgraduate medicine', description:'Interpret diagnostic evidence, treatment effects and uncertainty.'},
  publicHealth: {title:'Public health postgraduate', description:'Work with population comparisons, bias and study design.'}
};
const options = (...rows) => rows.map(([text, feedback], i) => ({id:String.fromCharCode(65+i), text, feedback}));
export const questions = [
 {id:'UG-SENS-01',version:1,track:'foundation',topic:'Sensitivity',
  objective:'Choose the denominator for sensitivity.',
  stem:'In a fictional diagnostic study, 90 people have the condition and 810 do not. The test is positive in 72 of the 90 people with the condition and in 81 of the 810 without it. What is the sensitivity?',
  options:options(['20%','This is the false-negative proportion: 18/90.'],['47.1%','This is the positive predictive value: 72/(72+81).'],['80%','Use the people with the condition as the denominator: 72/90.'],['90%','This is the specificity: 729/810.'],['97.6%','This is the negative predictive value: 729/(729+18).']),correct:'C',
  hint:'Start with the people known to have the condition. How many did the test detect?',
  lesson:'Sensitivity asks: among people with the condition, what proportion test positive? Positive predictive value reverses the question: among people with a positive result, what proportion have the condition?',
  explanation:'Sensitivity = true positives / (true positives + false negatives) = 72/90 = 80%. The 81 false positives matter for specificity and predictive values, not for this denominator.',
  calculation:{kind:'sensitivity',tp:72,fn:18,expected:0.8},help:'clinical_epidemiology/diagnostic.htm',operation:'MiscDiagnostic'},
 {id:'UG-NNT-01',version:2,track:'foundation',topic:'Absolute benefit and NNT',
  objective:'Calculate NNT and retain the follow-up period.',
  stem:'With complete one-year follow-up, an individually randomised trial records at least one unplanned admission in 16 of 200 programme participants and 28 of 200 usual-care participants. Using these point estimates, what is the number needed to treat to prevent one additional person having an admission over one year, rounded up to a whole person?',
  options:options(['6','Six percentage points is the absolute risk reduction, not its reciprocal.'],['7','The absolute reduction is 0.06, so its reciprocal is larger than 7.'],['12','Twelve is the difference in event counts, not NNT.'],['17','1/(0.14−0.08) = 16.67, rounded up to 17.'],['43','About 43% is the relative risk reduction; NNT uses absolute risk reduction.']),correct:'D',
  hint:'Calculate the two event risks, subtract them, then take the reciprocal of that absolute difference.',
  lesson:'NNT connects an absolute reduction in risk to the number of people treated. It depends on baseline risk, the outcome and the follow-up period. Count people with an outcome, not repeated events. A point estimate alone does not describe uncertainty or establish benefit.',
  explanation:'Usual-care risk is 28/200 = 0.14. Programme risk is 16/200 = 0.08. The absolute reduction is 0.06, so NNT = 16.67, conventionally rounded up to 17, for this outcome over one year.',
  calculation:{kind:'nnt',controlEvents:28,controlN:200,treatmentEvents:16,treatmentN:200,expected:17},help:'clinical_epidemiology/nnt.htm',operation:'MiscNumberNeededToTreat'},
 {id:'UG-PVAL-01',version:1,track:'foundation',topic:'P values',
  objective:'Interpret a P value conditional on a null model.',
  stem:'A prespecified two-sided analysis gives P = 0.03. Which interpretation is most accurate?',
  options:options(['The null hypothesis has a 3% probability of being true.','A P value is not a posterior probability for the null hypothesis.'],['If the null model and its assumptions hold, a test statistic at least as extreme as this has probability 3%.','This is the repeated-sampling interpretation under the specified null model.'],['The treatment has a 97% probability of working.','A P value does not give the probability that a treatment works.'],['The estimated treatment effect is clinically important.','Clinical importance depends on the effect size, uncertainty, harms and context.'],['There is a 3% probability that the study contains any bias.','P values do not measure the probability of bias.']),correct:'B',
  hint:'Which statement starts by assuming the null model, rather than assigning a probability to it?',
  lesson:'A P value measures compatibility with a specified null model using a chosen test statistic. It does not determine clinical importance or rule out bias. Read it alongside the effect estimate and confidence interval.',
  explanation:'The probability refers to possible test statistics under the null model and its assumptions. It is not the probability that the null is true, that the finding is a chance accident, or that the effect matters clinically.',
  help:'basics/p_values.htm',operation:null},
 {id:'UG-PAIR-01',version:1,track:'foundation',topic:'Choosing a paired analysis',
  objective:'Match a comparison to its paired structure.',
  stem:'Eighteen independently sampled adults each have a measurement before and after an intervention. Their within-person differences are approximately normally distributed, with no major outliers. Which test directly assesses whether the population mean change is zero?',
  options:options(['Unpaired t test','Treating the observations as independent loses the within-person pairing.'],['Pearson chi-square test','This is not a comparison of categorical counts.'],['Mann–Whitney test','This test is for independent groups, not paired observations.'],['Paired t test','The paired t test is a one-sample t test of the within-person differences.'],['Pearson correlation test','Correlation measures association, not whether the mean change is zero.']),correct:'D',
  hint:'What single value could you compute for each participant?',
  lesson:'Subtract each person’s before value from their after value, using the same direction for everyone. The paired t test operates on those differences. The normality assumption concerns the differences.',
  explanation:'Use a paired t test on the 18 within-person differences. A before–after change alone does not establish that the intervention caused it; a causal claim needs an appropriate study design.',
  help:'parametric_methods/paired_t.htm',operation:'TPaired'},
 {id:'PG-PPV-01',version:1,track:'medicine',topic:'Predictive value and prevalence',
  objective:'Combine prevalence, sensitivity and specificity.',
  stem:'A fictional screening test has sensitivity 90% and specificity 95%. Assume these apply in a population with prevalence 1%. Approximately what proportion of positive results would be true positives?',
  options:options(['1%','Prevalence is the probability before seeing the test result.'],['5%','This is the false-positive rate among people without the condition.'],['15.4%','For 10,000 people, expect 90 true positives and 495 false positives: 90/585.'],['90%','Sensitivity conditions on having the condition, not on a positive test.'],['95%','Specificity conditions on not having the condition.']),correct:'C',
  hint:'Imagine 10,000 people. Work out true positives and false positives separately.',
  lesson:'At low prevalence, people without the condition greatly outnumber those with it. Even a modest false-positive rate can therefore produce many false positives. Keep sensitivity and predictive value separate.',
  explanation:'Among 10,000 people, 100 have the condition, producing 90 true positives. The other 9,900 produce 495 false positives. PPV = 90/(90+495) = 15.38%.',
  calculation:{kind:'ppv',prevalence:0.01,sensitivity:0.9,specificity:0.95,expected:0.15384615384615385},help:'clinical_epidemiology/diagnostic.htm',operation:'MiscDiagnostic'},
 {id:'PG-CI-01',version:2,track:'medicine',topic:'Confidence intervals',
  objective:'Distinguish inconclusive evidence from evidence of no effect.',
  stem:'A trial estimates a treatment-to-control risk ratio for an adverse outcome of 0.76 with a 95% confidence interval from 0.58 to 1.03. Which conclusion best describes these results?',
  options:options(['The trial proves that the intervention has no effect.','Including 1 does not prove the absence of an effect.'],['The results are compatible with appreciable benefit and a small increase in risk; they do not exclude no effect.','The interval spans a 42% reduction through a 3% increase and includes a risk ratio of 1.'],['There is a 95% probability that this particular interval contains the true effect.','That is not the frequentist repeated-sampling interpretation of a confidence interval.'],['The intervention reduces risk by exactly 24% in every patient.','A group-level point estimate is uncertain and is not an individual guarantee.'],['Increasing the sample size would guarantee a statistically significant benefit.','A larger sample can improve precision but cannot guarantee that conclusion.']),correct:'B',
  hint:'For a ratio, what value represents no difference? What range of effects does the interval allow?',
  lesson:'For risk ratios the null value is 1; for risk differences it is 0. An interval that includes the null can also include important benefit or harm. Its width tells you about precision.',
  explanation:'The estimate favours benefit, but the interval includes no effect and a small increase in risk. Interpret the magnitude and precision together; clinical decisions also require harms, costs and other evidence.',
  help:'basics/confidence_interval.htm',operation:'PropUnPaired'},
 {id:'PG-RROR-01',version:2,track:'medicine',topic:'Risk and odds',
  objective:'Recognise that odds ratios and risk ratios differ for common outcomes.',
  stem:'In a fictional cohort, an outcome occurs in 120 of 200 exposed people and 80 of 200 unexposed people. Which pair gives the exposed-to-unexposed risk ratio and odds ratio?',
  options:options(['Risk ratio 1.50; odds ratio 2.25','Risks are 0.6 and 0.4; odds are 120/80 and 80/120.'],['Risk ratio 2.25; odds ratio 1.50','These two statistics have been exchanged.'],['Risk ratio 1.50; odds ratio 1.50','These outcomes are common: the odds ratio is 2.25, not 1.50. Rarity in both groups is a useful sufficient condition for the usual risk-ratio approximation.'],['Risk ratio 0.67; odds ratio 0.44','These compare unexposed with exposed, reversing the requested direction.'],['Risk ratio 0.20; odds ratio 0.20','0.20 is the absolute risk difference.']),correct:'A',
  hint:'Risk divides events by everyone in the group. Odds divides events by non-events.',
  lesson:'Always identify the reference group. Risks and odds are different quantities; with common outcomes, an odds ratio can be much further from 1 than the corresponding risk ratio.',
  explanation:'RR = (120/200)/(80/200) = 1.5. OR = (120/80)/(80/120) = 2.25. These observational comparisons do not by themselves establish causation.',
  calculation:{kind:'riskOdds',a:120,b:80,c:80,d:120,expected:[1.5,2.25]},help:'clinical_epidemiology/risk_prospective.htm',operation:'MiscRelRisk'},
 {id:'PG-SE-01',version:1,track:'medicine',topic:'Precision and sample size',
  objective:'Apply the square-root relationship between sample size and standard error.',
  stem:'For independent observations from the same population, assume the standard deviation stays fixed. If the sample size increases from 100 to 400, what happens to the standard error of the sample mean?',
  options:options(['It is unchanged.','The standard error depends on sample size even when the population standard deviation is unchanged.'],['It becomes one quarter as large.','Standard error falls with the square root of sample size, not sample size itself.'],['It doubles.','A larger independent sample makes the mean more precise.'],['It becomes half as large.','SE = SD/√n, so the ratio is √(100/400) = 0.5.'],['It becomes zero.','Finite samples retain sampling uncertainty.']),correct:'D',
  hint:'Use SE = SD divided by the square root of n.',
  lesson:'Standard deviation describes variation between observations; standard error describes sampling variation in an estimate. Quadrupling an independent sample halves the standard error when the standard deviation stays fixed.',
  explanation:'SE(new)/SE(old) = √100/√400 = 0.5. Dependence or clustering changes the calculation, and systematic bias is not removed by increasing sample size.',
  calculation:{kind:'seRatio',oldN:100,newN:400,expected:0.5},help:'basics/precision.htm',operation:'UnivariateSummary'},
 {id:'PH-STAND-01',version:1,track:'publicHealth',topic:'Direct standardisation',
  objective:'Apply common population weights to age-specific rates.',
  stem:'A district has annual mortality rates of 200 per 100,000 in its younger age group and 1,000 per 100,000 in its older group. A standard population contains 75% younger and 25% older people. What is the directly age-standardised annual rate per 100,000?',
  options:options(['200','This uses only the younger group.'],['300','The weighted contribution of the older group alone is 250, in addition to 150 from the younger group.'],['400','0.75 × 200 + 0.25 × 1,000 = 400.'],['600','This would use equal weights rather than the supplied standard population.'],['1,200','Adding the rates ignores the population weights.']),correct:'C',
  hint:'Multiply each age-specific rate by its share of the standard population, then add.',
  lesson:'Direct standardisation applies each population’s stratum-specific rates to a common set of weights. The resulting rate is a comparison summary, not necessarily the population’s observed crude rate.',
  explanation:'The younger contribution is 150 and the older contribution is 250, giving 400 per 100,000 per year. Use the same standard weights when comparing districts.',
  calculation:{kind:'weightedRate',rates:[200,1000],weights:[0.75,0.25],expected:400},help:'rates/direct_standardization.htm',operation:'RateDirectScreen'},
 {id:'PH-CONF-01',version:2,track:'publicHealth',topic:'Confounding',
  objective:'Interpret a change between crude and stratified associations.',
  stem:'An observational comparison gives a crude risk ratio of 2.0. Baseline age precedes exposure, influences exposure choice and predicts the outcome; the exposed group is older. In every age stratum the risk ratio is 1.0, with adequate data and accurate measurement. Which explanation is most consistent with this pattern?',
  options:options(['The pattern is consistent with confounding by baseline age.','Different age distributions can create a crude association when no association remains within age strata.'],['Age is certainly a mediator of the exposure effect.','Baseline age precedes exposure, so it cannot mediate the effect of that exposure.'],['There must be strong effect modification by age.','The stated stratum-specific risk ratios do not vary with age; effect modification must be described on a specified scale.'],['The exposure has been proved harmless in every setting.','Removing this observed association does not establish universal safety or remove other biases.'],['The crude risk ratio is necessarily an arithmetic error.','A correctly computed crude ratio can differ from stratum-specific ratios.']),correct:'A',
  hint:'Distinguish imbalance in a third variable from variation of the effect across strata.',
  lesson:'Confounding can mix the effect of an exposure with differences in other determinants of the outcome. Effect modification describes variation across strata on a specified effect scale, such as a risk difference or risk ratio. A causal diagram and design knowledge help decide what to adjust for.',
  explanation:'Given the stated causal role and imbalance of baseline age, this pattern supports age confounding. A change after adjustment alone cannot diagnose confounding or establish no causal effect; chance, other biases and the causal assumptions still matter.',
  help:'basics/confounding.htm',operation:'MantelHaenszelScreen'},
 {id:'PH-CLUST-01',version:1,track:'publicHealth',topic:'Clustered observations',
  objective:'Recognise the loss of precision from within-cluster correlation.',
  stem:'A survey uses equal clusters of 20 people. For its outcome, the intracluster correlation is 0.04. Using the approximation DE = 1 + (m − 1)ρ, what is the design effect relative to simple random sampling?',
  options:options(['1.04','The correlation is multiplied by m−1, not added just once.'],['1.20','Insert m = 20 and ρ = 0.04 into the stated formula.'],['1.76','1 + 19 × 0.04 = 1.76.'],['2.00','The supplied values give a smaller variance inflation.'],['20.00','A design effect of 20 under this formula would require perfect within-cluster correlation.']),correct:'C',
  hint:'Here m is the number of people in each cluster, not the number of clusters.',
  lesson:'People in one cluster may provide partly overlapping information. This approximation multiplies the variance by the design effect; standard errors are multiplied by its square root. Unequal cluster sizes and few clusters need more careful planning.',
  explanation:'DE = 1 + (20−1) × 0.04 = 1.76. Under this approximation, nominal sample size divided by 1.76 gives an effective sample size; it is not a substitute for a full cluster-design calculation.',
  calculation:{kind:'designEffect',m:20,rho:0.04,expected:1.76},help:'basics/precision.htm',operation:null},
 {id:'PH-SMR-01',version:2,track:'publicHealth',topic:'Standardised mortality ratio',
  objective:'Interpret observed relative to expected events.',
  stem:'A population has 55 observed deaths over the study period. Applying reference age-specific mortality rates to its age-specific person-time gives 44 expected deaths. What is the standardised mortality ratio, expressed as a ratio rather than a percentage?',
  options:options(['0.20','This is neither the observed-to-expected ratio nor its reciprocal.'],['0.80','This reverses observed and expected.'],['1.25','55/44 = 1.25.'],['11','Eleven is the difference in counts.'],['125','125 is the SMR expressed on a percentage scale, not the requested ratio scale.']),correct:'C',
  hint:'Use observed deaths divided by expected deaths.',
  lesson:'An SMR compares observed with expected events based on reference stratum-specific rates. Always state whether you use a ratio scale (null 1) or percentage scale (null 100), and include uncertainty. SMRs for different populations may use different implicit weights, so they are not automatically comparable with each other.',
  explanation:'SMR = 55/44 = 1.25, or 25% more deaths than expected on this reference. The point estimate alone does not establish statistical significance or causation.',
  calculation:{kind:'smr',observed:55,expectedDeaths:44,expected:1.25},help:'rates/smr.htm',operation:'RateSmrScreen'}
];

tracks.analyst = {title:'Healthcare / business analyst', description:'Describe services, compare performance and communicate uncertainty.'};
tracks.researcher = {title:'Researcher / degree module', description:'Choose methods, check assumptions and interpret research evidence.'};
questions.push(
 {id:'AN-MED-01',version:1,track:'analyst',topic:'Skewed service data',objective:'Choose a resistant description of a typical waiting time.',stem:'Most clinic waits are 10–25 minutes, but a few exceed two hours. Which summary is least affected by these unusually long waits when describing a typical patient’s wait?',options:options(['Mean and standard deviation','Both are influenced by unusually large values.'],['Median and interquartile range','The median describes the middle observation and the IQR the middle half.'],['Maximum only','The maximum describes an extreme, not a typical observation.'],['Standard error only','This concerns precision of an estimate, not a typical wait.'],['P value','This does not describe the distribution.']),correct:'B',hint:'Consider a measure based on ordered positions rather than the sum.',lesson:'Use a histogram with median and IQR for a resistant summary, while retaining the long waits as operationally important observations.',explanation:'Median and IQR resist the influence of extreme waits. They do not make long waits irrelevant: report tail performance separately when it matters.',help:'basic_descriptive_statistics/univariate_summary.htm',operation:'UnivariateSummary'},
 {id:'AN-PCT-01',version:1,track:'analyst',topic:'Percentage points',objective:'Distinguish an absolute percentage-point change from a relative change.',stem:'The non-attendance rate falls from 10% to 8%. Which statement correctly describes both the absolute and relative reduction?',options:options(['2 percentage points; 20% relative reduction','(0.10−0.08)/0.10 = 0.20.'],['2 percentage points; 2% relative reduction','The relative reduction divides by the starting risk.'],['20 percentage points; 2% relative reduction','This reverses and mis-scales the changes.'],['8 percentage points; 80% relative reduction','These describe the new rate or its ratio, not the reduction.'],['No reduction','The rate decreased.']),correct:'A',hint:'Subtract for the absolute change; divide that change by the starting value for the relative change.',lesson:'State both absolute and relative changes, and include denominators and time periods.',explanation:'The absolute fall is 0.02, or two percentage points. Relative to the original 0.10 it is a 20% reduction. These rates alone do not establish what caused the reduction.',help:'clinical_epidemiology/risk_prospective.htm',operation:'MiscRelRisk'},
 {id:'AN-CAUS-01',version:1,track:'analyst',topic:'Association and causation',objective:'Recognise confounding in service comparisons.',stem:'Hospitals with more specialist staff also have higher mortality. They receive the most severely ill patients. What is the best first interpretation?',options:options(['Specialists cause deaths','The observational comparison does not support this causal claim.'],['Severity may confound the association','Severity can affect staffing needs and mortality.'],['More staff must prevent every death','This is not supported either.'],['Mortality cannot be compared statistically','Comparisons are possible, with careful design and adjustment.'],['A small P value would eliminate confounding','Statistical significance does not remove systematic bias.']),correct:'B',hint:'What differs between the patients cared for by these hospitals?',lesson:'Case mix is essential to interpreting service comparisons. Adjustment needs design knowledge and measured relevant variables.',explanation:'Severity is a plausible confounder. Compare like with like where possible and describe remaining limitations; an adjusted model alone does not prove causation.',help:'basics/confounding.htm',operation:null},
 {id:'AN-PREC-01',version:2,track:'analyst',topic:'Precision of a rate',objective:'Relate denominators to uncertainty.',stem:'Two services both observe a 10% event rate. One records 10 events among 100 people, the other 100 among 1,000. Using the same confidence level and binomial interval method, and independent comparable observations, which usually has the narrower interval for the underlying proportion?',options:options(['The service with 100 people','It has less information about the population proportion.'],['The service with 1,000 people','A larger independent denominator improves precision at the same observed rate.'],['Both must have identical intervals','Equal point estimates can have different uncertainty.'],['Neither can have an interval','A confidence interval can be calculated for either proportion.'],['The service with the smaller P value, regardless of denominator','The question concerns precision of an estimated rate.']),correct:'B',hint:'Consider the standard error √(p(1−p)/n).',lesson:'Show denominators and uncertainty alongside performance rates.',explanation:'At the same rate, a larger independent sample generally gives a narrower interval. Clustering, bias and different case mix can complicate real comparisons.',help:'basics/confidence_interval.htm',operation:null},
 {id:'RS-PAIR-01',version:1,track:'researcher',topic:'Paired assumptions',objective:'Identify the relevant distributional assumption for a paired t test.',stem:'Which distribution should be checked for major departures from normality when using a paired t test with a small sample of independent pairs?',options:options(['The pooled before and after measurements','Pooling ignores pairing.'],['The within-pair differences','The test is a one-sample t test of these differences.'],['The participant identification numbers','Identifiers have no relevant distribution.'],['The P values','These are outputs rather than the observations being modelled.'],['Only the before measurements','The test operates on differences.']),correct:'B',hint:'What single observation enters the test for each pair?',lesson:'Check differences and the independence of pairs; investigate outliers and whether the study design supports the intended inference.',explanation:'The paired t test models within-pair differences. It does not require the two original measurement distributions individually to be normal.',help:'parametric_methods/paired_t.htm',operation:'TPaired'},
 {id:'RS-MULT-01',version:2,track:'researcher',topic:'Multiple testing',objective:'Recognise false-positive risk across many tests.',stem:'Twenty tests are independent under their null hypotheses, which are all true. Each test has an actual false-positive probability of 5%. What is the probability of at least one false positive, approximately?',options:options(['5%','This is the level for one test, not the whole family.'],['10%','Use the probability of no false positives across all tests.'],['36%','This is approximately the probability of no false positives.'],['64%','1−0.95^20 is approximately 0.642.'],['100%','A false positive is not guaranteed.']),correct:'D',hint:'The chance of no false positives is 0.95 multiplied by itself twenty times.',lesson:'Prespecify analyses and distinguish confirmatory from exploratory work. Multiplicity affects interpretation.',explanation:'Under the stated independence assumption, P(at least one) = 1−0.95^20 ≈ 64.2%. Dependence changes this calculation.',help:'basics/p_values.htm',operation:null},
 {id:'RS-MISS-01',version:1,track:'researcher',topic:'Missing data',objective:'Recognise bias from outcome-related missingness.',stem:'Participants with the worst symptoms are more likely to miss their follow-up visit. What is the main concern with analysing only complete records?',options:options(['It necessarily removes all bias','Removing missing records does not fix selective follow-up.'],['It always gives the same result as full follow-up','Missingness can depend on outcomes.'],['It may produce a biased estimate as well as lose precision','Complete cases may systematically differ from those missing.'],['It proves the symptoms improved','Non-attendance is not an observed improvement.'],['A larger sample guarantees no bias','More observations do not remove systematic selection.']),correct:'C',hint:'Are the observed participants representative of everyone originally enrolled?',lesson:'Describe missingness, investigate its causes and justify assumptions for sensitivity analyses or imputation.',explanation:'Outcome-related missingness can make complete cases unrepresentative. The direction and size of bias depend on the setting and missingness process.',help:'basics/bias.htm',operation:null},
 {id:'RS-CI-01',version:1,track:'researcher',topic:'Confidence interval interpretation',objective:'Interpret repeated-sampling coverage.',stem:'What does a 95% frequentist confidence procedure aim to achieve under its assumptions?',options:options(['95% of individual observations lie in every interval','This confuses a parameter interval with a range of observations.'],['95% of intervals from repeated samples contain the fixed population parameter','Coverage refers to the procedure across repeated samples.'],['The null hypothesis is true with probability 95%','This is not a posterior probability.'],['95% of future studies give exactly the same estimate','Estimates vary between samples.'],['Bias is eliminated in 95% of studies','Coverage relies on model and design assumptions.']),correct:'B',hint:'Imagine repeating the sampling and interval calculation many times.',lesson:'A confidence interval reports precision under assumptions; it does not protect against every source of bias.',explanation:'The 95% refers to long-run coverage of the fixed parameter by the interval procedure, provided the relevant assumptions hold.',help:'basics/confidence_interval.htm',operation:null}
);

// Additional original items following review of publicly published examination examples.
// The inspiration tags identify topic/format references, not copied questions or endorsements.
questions.push(
 {id:'PG-ROC-01',version:2,track:'medicine',topic:'Diagnostic thresholds',objective:'Recognise the sensitivity–specificity trade-off.',stem:'In a fictional study, a blood marker is considered positive above a chosen cut-off. Researchers raise that cut-off while keeping the same participants and reference diagnoses. Which change in classification is possible?',options:options(['Some previously negative results become positive','Raising the cut-off cannot do this on the same data.'],['Some true positives and false positives become negative','A higher cut-off can reduce both true-positive and false-positive counts.'],['Sensitivity must increase','A higher cut-off cannot capture additional positive cases on the same data.'],['Specificity must decrease','With the same disease-negative denominator, fewer false positives mean higher specificity; with none changing, specificity is unchanged.'],['Both denominators change automatically','Disease status is fixed by the reference diagnoses in this study.']),correct:'B',hint:'Think about people whose marker lies between the old and new cut-offs.',lesson:'Choosing a threshold changes the balance of missed cases and false alarms. Inspect sensitivity and specificity together; predictive values also depend on the setting.',explanation:'Values between the two cut-offs change from positive to negative. This can lower sensitivity and raise specificity; if nobody falls between the cut-offs the classifications stay unchanged.',help:'clinical_epidemiology/diagnostic.htm',operation:'MiscDiagnostic',inspiration:'Public MRCP-style diagnostic threshold examples; original scenario and options.'},
 {id:'PG-LR-01',version:1,track:'medicine',topic:'Pre-test and post-test probability',objective:'Update odds with a likelihood ratio.',stem:'For a fictional test, the positive likelihood ratio is 6. Before testing, the probability of the condition is 10%. What is the approximate probability after a positive result, assuming the likelihood ratio applies in this setting?',options:options(['6%','The likelihood ratio is a multiplier of odds, not a probability.'],['16%','Adding a likelihood ratio to a probability is not valid.'],['40%','Prior odds 1/9 become 6/9; probability is (6/9)/(1+6/9) = 0.4.'],['60%','Multiply odds, rather than multiplying the probability by 6.'],['100%','A positive test does not guarantee the condition.']),correct:'C',hint:'First convert the 10% probability to odds p/(1−p).',lesson:'Likelihood ratios update odds. Convert back to a probability after multiplication.',explanation:'Pre-test odds = 0.1/0.9 = 1/9. Post-test odds = 6/9 = 2/3. Post-test probability = (2/3)/(1+2/3) = 0.4, or 40%.',help:'clinical_epidemiology/diagnostic.htm',operation:'MiscDiagnostic',inspiration:'Public MRCP-style diagnostic evidence teaching; independently constructed numerical question.'},
 {id:'PG-FOREST-01',version:2,track:'medicine',topic:'Interpreting effect estimates',objective:'Distinguish effect size from statistical evidence.',stem:'Two fictional studies estimate treatment-to-control risk ratios for the same adverse outcome. Study A: 0.40 (95% CI 0.10–1.60). Study B: 0.85 (95% CI 0.80–0.91). Assuming valid corresponding two-sided tests, which interpretation is best?',options:options(['Study A has stronger evidence solely because its ratio is further from 1','Effect magnitude alone does not measure statistical evidence.'],['Only Study B rejects the null risk ratio of 1 at the 5% level','Study B’s interval excludes 1; Study A’s includes it.'],['Study A proves there is no benefit','Its wide interval includes both substantial benefit and harm.'],['Study B necessarily has the more important clinical benefit','Clinical importance needs context and absolute risks.'],['Both intervals exclude no effect','Study A includes the null ratio of 1.']),correct:'B',hint:'Inspect whether each confidence interval includes the null ratio of 1.',lesson:'Read the point estimate and interval together. A large but imprecise estimate does not automatically provide stronger evidence than a smaller, precise one.',explanation:'Only Study B’s interval excludes 1. This does not settle clinical importance, bias, comparability or a direct difference between the two studies.',help:'basics/confidence_interval.htm',operation:null,inspiration:'RCGP November 2025 data-interpretation samples, especially Q41; new example separating magnitude from evidence.'},
 {id:'AN-RATE-01',version:1,track:'analyst',topic:'Rates versus counts',objective:'Avoid inferring absolute totals from a rate alone.',stem:'A chart shows Clinic A with 24 referrals per 1,000 registered patients and Clinic B with 18 per 1,000 during the same quarter. Their registered populations are not supplied. Which conclusion is justified by these values alone?',options:options(['Clinic A made more referrals in total','The population denominators are unknown.'],['Clinic B has fewer registered patients','The rates do not reveal population sizes.'],['Clinic A has the higher referral rate','24 per 1,000 exceeds 18 per 1,000.'],['Clinic A’s referrals were less appropriate','No appropriateness data are supplied.'],['Clinic B provides better care','A rate alone does not establish quality.']),correct:'C',hint:'What does “per 1,000” tell you, and what does it leave unknown?',lesson:'Read the axis units and distinguish counts from rates. Rates support comparison but do not by themselves explain quality or total workload.',explanation:'Only the rate comparison follows. Total referrals also depend on population size; appropriateness and quality require additional evidence.',help:'rates/incidence_and_prevalence.htm',operation:null,inspiration:'RCGP November 2025 Q3 and Q20: interpretation of plotted rates; original referral scenario.'},
 {id:'PH-CASEMIX-01',version:2,track:'publicHealth',topic:'Case mix and service comparisons',objective:'Identify what is needed before attributing a difference to performance.',stem:'A rehabilitation unit has a higher average length of stay than another unit. It also receives more people with complex disability and has longer waits for supported housing. Which is the most defensible next step?',options:options(['Conclude that its clinical team is inefficient','The crude average mixes performance with patient needs and discharge circumstances.'],['Delete every stay longer than the median','Arbitrary exclusion loses relevant information and may bias the comparison.'],['Examine the distribution, case mix and discharge pathways before judging performance','All can explain differences in the crude mean.'],['Compare only the two largest stays','Extremes alone cannot characterise the services.'],['Ignore all service comparisons','Careful comparisons can be useful.']),correct:'C',hint:'What factors beyond treatment quality influence how long someone stays?',lesson:'Combine descriptive statistics with service context. Investigate skew, recording conventions, patient needs and discharge support.',explanation:'Distribution, case mix and the wider care pathway matter. Adjusted comparisons still require appropriate data and assumptions; a crude mean alone cannot attribute causation. Define whether discharge support is part of the service effect being evaluated before deciding to adjust for it.',help:'basic_descriptive_statistics/univariate_summary.htm',operation:'UnivariateSummary',inspiration:'FPH DFPH Specimen Paper B Q1: interpretation and case mix; new setting and single-best-answer format.'},
 {id:'RS-LEAD-01',version:1,track:'researcher',topic:'Screening and lead-time bias',objective:'Distinguish earlier diagnosis from longer life.',stem:'A fictional screening programme diagnoses a disease two years earlier, but people die at the same age they would have without screening. Measured survival from diagnosis rises. What explains this rise?',options:options(['A demonstrated reduction in mortality','Death timing has not changed.'],['Lead-time bias','Earlier diagnosis starts the survival clock sooner without postponing death.'],['Randomisation','The scenario does not describe random allocation.'],['A guaranteed treatment benefit','Longer measured survival alone does not establish benefit.'],['A fall in disease incidence','No such change is stated.']),correct:'B',hint:'Which event starts the survival clock?',lesson:'Screening evaluation needs outcomes that distinguish earlier detection from improved health. Consider harms and appropriate comparisons.',explanation:'Lead-time bias extends observed time from diagnosis to death when diagnosis happens earlier but death does not. Mortality and other patient-relevant outcomes are needed to assess benefit.',help:'basics/bias.htm',operation:null,inspiration:'FPH critical-appraisal and screening specimens: original bias question.'}
);

// Epidemiology and causal reasoning are shared foundations in every pathway.
questions.push(
 {id:'CORE-DESIGN-01',version:2,track:'core',topic:'Study design and denominators',objective:'Recognise outcome-based sampling in a case-control study.',stem:'Researchers select 120 people with a disease and 240 without it, then compare previous exposure. Which statement best describes what can be estimated directly from this sampling design?',options:options(['The population incidence, using 120/360','The numbers with and without disease were selected by design.'],['An exposure odds ratio, with suitable control selection and assumptions','Case-control sampling can estimate an odds ratio; it does not directly give population risk from these group sizes.'],['The population prevalence, using 120/360','The investigator fixed the case-control ratio.'],['The causal risk difference with no further assumptions','Causal interpretation needs design and confounding assumptions.'],['The number needed to treat from case counts alone','Absolute treatment risks are not supplied.']),correct:'B',hint:'Were participants sampled before or after their outcome status was known?',lesson:'Study design determines which denominators and measures have meaning. Recognise case-control, cohort and experimental designs before choosing a statistic.',explanation:'The investigator chooses cases and controls, so their proportion in the sample is not population incidence or prevalence. The meaning of the odds ratio depends on control sampling. Sampling controls from the risk sets can estimate an incidence rate ratio without a rare-disease assumption. Sampling non-cases at the end of a fixed period instead targets an odds ratio for cumulative risk. Causal interpretation needs additional assumptions.',help:'clinical_epidemiology/risk_retrospective.htm',operation:'MiscRetroRisk'},
 {id:'CORE-RATE-01',version:2,track:'core',topic:'Incidence rate and person-time',objective:'Distinguish an incidence rate from a cumulative risk.',stem:'A fictional cohort contributes 600 person-years while participants are at risk, with 12 new events. What is the incidence rate?',options:options(['2 events per 100 person-years','12/600 = 0.02 events per person-year.'],['2% of participants, regardless of follow-up','Person-time is not a count of participants.'],['12% per participant','The participant denominator is not given.'],['50 events per person-year','This inverts the rate.'],['600 events per year','600 is follow-up time, not event count.']),correct:'A',hint:'Divide events by total time at risk, then state the units.',lesson:'An incidence rate uses person-time at risk. A risk uses people initially at risk over a specified period, with appropriate treatment of incomplete follow-up.',explanation:'12/600 = 0.02 events per person-year, or 2 per 100 person-years. This cannot automatically be read as a two-percent one-year risk.',help:'rates/incidence_and_prevalence.htm',operation:null},
 {id:'CORE-MEDIATOR-01',version:2,track:'core',topic:'Confounders and mediators',objective:'Match adjustment to the causal effect of interest.',stem:'A randomised exercise intervention can affect blood pressure partly by changing body weight. To estimate the total intervention effect on blood pressure, why might routinely adjusting for weight measured after the intervention be inappropriate?',options:options(['Post-intervention weight is necessarily a baseline confounder','It is measured after treatment and may be affected by it.'],['It can block part of the pathway through which the intervention acts','That pathway contributes to the total effect.'],['Adjustment always increases bias in every analysis','Appropriate adjustment depends on the target effect and causal structure.'],['Randomisation proves that weight is irrelevant','Weight may still mediate treatment effects.'],['A smaller P value decides which variables to adjust for','Variable choice should follow the causal question and assumptions.']),correct:'B',hint:'Distinguish a variable that precedes treatment from one affected by treatment.',lesson:'For a total effect, mediators are part of the causal pathway. Direct effects ask a different question and require additional identification assumptions; adding a mediator to a regression does not automatically estimate a causal direct effect.',explanation:'Adjusting for a mediator can remove part of the total effect and may introduce other bias. Define the estimand and causal structure before deciding what to adjust for.',help:'basics/confounding.htm',operation:null},
 {id:'CORE-SELECTION-01',version:2,track:'core',topic:'Selection and collider bias',objective:'Recognise bias caused by conditioning on a common consequence.',stem:'In a fictional population, exposure E and illness Y both influence whether someone attends a specialist clinic. A study includes only clinic attendees. Even if E and Y were otherwise unrelated, what problem could this selection create?',options:options(['It guarantees a representative population sample','Attendance selects people through both variables.'],['It may create an association by conditioning on a common consequence','Attendance can act as a collider between E and Y.'],['It eliminates confounding automatically','Selection does not guarantee comparability.'],['It proves E causes Y','The selection process can create a non-causal association.'],['It can only reduce random error','It can introduce systematic bias.']),correct:'B',hint:'Consider the arrows E → attendance ← Y.',lesson:'Conditioning on a common consequence can open a non-causal association. Eligibility, recruitment, follow-up and analysis restrictions can all matter.',explanation:'Selecting on clinic attendance conditions on a potential collider and can create an association between its causes. The direction and magnitude depend on the data-generating process.',help:'basics/bias.htm',operation:null}
);
