import {safeURL,validEmail,assessmentTypes,assessmentNotes} from './provider-course.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function trainingHTML(state,pack){const t=state.training;return `
<section class="card" id="trainingProvider"><h2>Your training provider</h2>
<label for="courseTitle">Course</label><input id="courseTitle" maxlength="200" value="${esc(t.courseTitle)}" placeholder="For example: www.statisticalhelp.org/help">
<div class="form-row"><div><label for="reviewEmail">Assessment email address</label><input id="reviewEmail" type="email" maxlength="254" value="${esc(t.reviewEmail)}" placeholder="support@statisticalhelp.org"></div><div><label for="assessmentType">Assessment type</label><select id="assessmentType">${Object.entries(assessmentTypes).map(([id,title])=>`<option value="${id}" ${t.assessmentType===id?'selected':''}>${esc(title)}</option>`).join('')}</select></div></div>
<p class="small" id="assessmentNote">${esc(assessmentNotes[t.assessmentType])}</p>
<div class="course-pack"><h3>A course pack from your tutor</h3>
<p>${pack?`<strong>${esc(pack.title)}</strong> · ${pack.documents.length} document(s) or pages`:'Add course notes, lessons, examples or practice questions.'}</p>
<div class="actions"><button id="importCourse">${pack?'Replace course pack…':'Import course pack…'}</button><button id="exampleCourse" class="link-button">Try example course</button></div>
<p class="small">PDF, Markdown, text or a StatsDirect course pack. Relevant extracts accompany questions you send to the tutor.</p>
${pack?`<details><summary>Included materials</summary><ul>${pack.documents.map(d=>`<li>${esc(d.title)}</li>`).join('')}</ul></details>`:''}</div>
<details class="option-details"><summary>Provider details and assessment conditions</summary>
<div class="form-row"><div><label for="providerName">Provider or university</label><input id="providerName" maxlength="200" value="${esc(t.providerName)}"></div><div><label for="courseVersion">Course version</label><input id="courseVersion" maxlength="80" value="${esc(t.courseVersion)}"></div></div>
<label for="requirements">Assessment requirements</label><textarea id="requirements" rows="2" maxlength="5000">${esc(t.requirements)}</textarea>
<label for="cpdStatement">Provider’s CPD or recognition conditions</label><textarea id="cpdStatement" rows="2" maxlength="2000">${esc(t.cpdStatement)}</textarea>
</details></section>`;}
export function bindTraining(state,{save}){
 const $=id=>document.getElementById(id);
 for(const key of ['providerName','courseTitle','courseVersion','reviewEmail','requirements','cpdStatement'])$(key).oninput=()=>{state.training[key]=$(key).value;save();};
 $('assessmentType').onchange=()=>{state.training.assessmentType=$('assessmentType').value;$('assessmentNote').textContent=assessmentNotes[state.training.assessmentType];save();};
}
export function courseWorkHTML(state,l){if(!l.providerCourse)return '';const saved=state.courseWork.filter(w=>w.lessonID===l.id);return `<details class="lesson-guide course-work"><summary>Practical work and course submission${saved.length?' · '+saved.length+' saved':''}</summary><p><strong>Learning objective:</strong> ${esc(l.objective)}</p><p>${esc(l.challenge)}</p>${(l.readingURLs??[]).map(u=>`<p><a href="${esc(safeURL(u))}" target="_blank" rel="noopener">Read course resource ↗</a></p>`).join('')}<label for="courseAnswer">Your answer, interpretation or practical findings</label><textarea id="courseAnswer" rows="4" maxlength="20000">${esc(state.workDrafts[l.id]??'')}</textarea><button id="saveCourseWork">Save submission to my learning record</button><p class="small">Each saved submission is retained for your provider to review. Attach report or R snapshots from My learning record.</p></details>`;}
export function providerRecordHTML(state,workspace){return `<section class="card"><h2>Course work and analysis evidence</h2><p>${esc(state.training.courseTitle||'No named course')} ${state.training.courseVersion?'· '+esc(state.training.courseVersion):''} · ${state.courseWork.length} practical submission(s)</p>${state.courseWork.map(w=>`<details><summary>${esc(w.lessonTitle)} · ${esc(new Date(w.at).toLocaleString())}</summary><p>${esc(w.text)}</p><p class="small">${esc(w.status)}</p></details>`).join('')}
<label for="evidenceDocument">Attach an open report or R session to this record</label><select id="evidenceDocument"><option value="">Choose a document…</option>${workspace.choices.filter(d=>d.kind==='report'||d.kind==='r').map(d=>`<option value="${esc(d.id)}">${esc(d.title)}</option>`).join('')}</select><button id="captureEvidence">Attach text snapshot</button><p class="small">The snapshot is stored locally in the record. Review it before emailing; original workbooks and chart images are not attached.</p>${state.evidence.map(e=>`<details><summary>${esc(e.title)} · ${esc(new Date(e.at).toLocaleString())}</summary><pre>${esc(e.text)}</pre></details>`).join('')}</section>
<section class="card"><h2>Returned assessments</h2><button id="importProviderReview">Import provider response…</button><p class="small">Import a response file returned by your provider for this learning record. StatsDirect records the supplied decision and feedback; it does not authenticate certificates or award credit.</p>${state.providerReviews.map(r=>`<article class="review-line"><strong>${esc(r.provider)} — ${esc(r.decision)}</strong><p>${esc(r.feedback)}</p><p>${esc(r.creditStatement)}</p><p class="small">${esc(r.reviewer)} · ${esc(r.reviewedAt)} · ${esc(r.verification)}</p></article>`).join('')}</section>`;}
export {validEmail};
