// Read on 25 September 2026. Link to source material; never embed exam-bank content.
export const examSources=[
 {title:'MRCP(UK): official Part 1 sample examination',url:'https://www.thefederation.uk/examinations/part-1/part-1-sample-questions',note:'Official best-of-five practice access. Registration is required; the questions behind that step were not reviewed for this build.'},
 {title:'MRCP-style diagnostic questions: published practice examples',url:'https://www.pastpaperhero.com/resources/rcp-mrcp-statistics-epidemiology-and-evidence-based-medicine-sensitivity-specificity-and-predictive-values?content=article',note:'Independent publisher, not a Royal College source. Public questions cover diagnostic denominators, prevalence and threshold changes. Used for topic inspiration only.'},
 {title:'MRCGP AKT: official sample questions and answers',url:'https://www.rcgp.org.uk/getmedia/dca96621-2599-4e6e-9a99-7a1ab2affff9/AKT-Example-Questions-(with-answers)-November-2025.pdf',note:'November 2025 samples include chart interpretation, event risk and uncertainty (questions 3, 10, 20, 24 and 41). The app uses new fictional examples.'},
 {title:'DFPH: official specimen papers and marking schemes',url:'https://www.fph.org.uk/training-careers/the-diplomate-dfph-and-final-membership-examination-mfph/the-diplomate-examination-dfph/the-diplomate-examination-dfph-preparation/',note:'Written interpretation and critical appraisal are important. The published Paper B includes interpretation of length of stay and case mix. These are not MCQ papers.'},
 {title:'MFPH: final membership assessment',url:'https://www.fph.org.uk/training-careers/the-diplomate-dfph-and-final-membership-examination-mfph/the-faculty-of-public-health-final-membership-examination/marking-results-and-feedback/',note:'Final membership assesses practical competencies across six stations. Use the conversational explanation exercise below alongside MCQ practice.'}
];
export const communicationPrompt='Practise a short public-health communication scenario with me. You are a fictional service manager asking whether a clinic with longer average waiting times is performing poorly. Give me a small original data example, ask me to explain it in plain language, and wait for my reply. Then give formative feedback on interpretation, case mix, uncertainty and clarity. Do not assign an official examination grade.';
