import {test} from 'node:test';
import assert from 'node:assert/strict';
import {WorkbookStore} from './workbook.mjs';
import {tutorData,tutorInfo} from './tutor-data.mjs';
const a=[312,242,340,388,296,254,391,402,290],b=[300,201,232,312,220,256,328,330,231];
function book(){const w=new WorkbookStore();w.load({name:'test.xlsx',sheets:[{name:'PEFR',rows:1000,columns:32,headerRow:true,cells:[...["Before","After","Other"].map((text,col)=>({col,row:0,text,kind:'text'})),...[a,b,[99]].flatMap((values,col)=>values.map((v,row)=>({col,row:row+1,text:String(v),kind:'number'})))]},{name:'Hidden',hidden:true,rows:1,columns:1,cells:[]}]});return w;}
test('selected PEFR columns contain exactly nine paired rows, no padded sheet area',()=>{const d=tutorData(book(),0,{columns:[0,1]});assert.equal(d.rowCount,9);assert.equal(d.firstRow,2);assert.equal(d.lastRow,10);assert.deepEqual(d.columns.map(c=>c.values),[a,b].map(v=>v.map(String)));assert.equal(d.complete,true);});
test('rectangular selection and column order are exact; internal blanks never shift a pair',()=>{const w=book();w.sheets[0].store.apply([[0,3,'']]);const d=tutorData(w,0,{columns:[1,0]},{firstRow:3,lastRow:5});assert.deepEqual(d.columns.map(c=>c.values),[['201','232','312'],['242',null,'388']]);assert.equal(d.rowCount,3);const rectangle=tutorData(w,0,{range:{x:0,y:1,width:2,height:2}});assert.deepEqual(rectangle.columns.map(c=>c.values),[['312','242'],['300','201']]);});
test('metadata has headings and selection but no cell values',()=>{const info=tutorInfo(book(),0,{columns:[0,1]});assert.equal(info.sheets[0].columns[0].title,'Before');assert.deepEqual(info.sheets[0].selection,[0,1]);assert.equal(JSON.stringify(info).includes('312'),false);});
test('hidden sheets, malformed arguments and oversized reads are rejected, never sampled',()=>{const w=book();for(const options of [{sheetIndex:1},{columns:'0'},{columns:[0,0]},{columns:[32]},{columns:[0,1,2],firstRow:1},{columns:[0,1,2],firstRow:2,lastRow:10000}])assert.throws(()=>tutorData(w,0,{},options));w.sheets[0].store.rows=10000;assert.throws(()=>tutorData(w,0,{}, {columns:[0,1],lastRow:3000}),/not been sampled/);assert.throws(()=>tutorData(w,0,{rows:[1,3]}),/continuous/);});
test('formula caches and Excel errors are exposed for native engine validation',()=>{const w=book(),s=w.sheets[0].store;s.metadata.set('0,1',{formula:'SUM(A3:A4)',kind:'number'});s.formulasStale=true;assert.equal(tutorData(w,0,{columns:[0,1]}).hasStaleFormulas,true);s.formulasStale=false;s.cells.set('0,1','');assert.equal(tutorData(w,0,{columns:[0,1]}).hasStaleFormulas,true);s.cells.set('1,1','#DIV/0!');s.metadata.set('1,1',{kind:'error',text:'#DIV/0!'});assert.equal(tutorData(w,0,{columns:[0,1]}).hasErrors,true);});
